### PR TITLE
implementation of nonlinear constraints

### PR DESCRIPTION
**Pull request by fserra**
a lot of code cleaning is needed, but here is there idea and the pull request

### CODE REVIEW

**Comment by fserra** [comment]
I just realize that we do not support `abs` yet :)

**Comment by leethargo** [comment]
I agree that this is the way to go. Let's merge after some clean up.

**Comment by leethargo** [comment]
Another topic for discussion: At the moment, the objective function and the objective sense are set independently of another. For the reformulation with an auxiliary variable and constraint, both need to be known. This also creates difficulties when the user changes the optimization sense later on.

To implement it, we could wait until `solve` is called and only perform the reformulation (internally) there, then undo it afterwards.

Alternatively, we could make the user specify the function and sense in the same function call and do the reformulation then.

**Comment by fserra** [comment]
Maybe leaving all the products at the end in `CSIPsetQuadObj` allows for simpler bookkeeping

**Comment by fserra** [comment]
> To implement it, we could wait until solve is called and only perform the reformulation (internally) there, then undo it afterwards.

Isn't that what we are doing?

**Comment by leethargo** [comment]
It seems to me that you already create a variable and a constraint in `CSIPsetNonlinearObj`.
In fact, do you create a new variable and constraint everytime this function is called (and don't reuse/remove the old one)?

**Comment by leethargo** [comment]
So, would you say that this is sufficiently cleaned up?

We could use a test with changing the (nonlinear) objective (sense)...

**Comment by fserra** [comment]
the test that changes the quadratic objective sense, is doing the nonlinear objective.

How much do we care about boundary cases? Set a quadratic objectve with empty data, etc? 

I would say this is ok for now, if somebody someday uses this and finds a problem then we fix it

**Pull request merged**
