### PR TITLE
implement CSIPgetObjBound

### PR DESCRIPTION
**Pull request by mlubin**
I was trying to address the failure of the mixintprog tests (https://github.com/leethargo/SCIP.jl/commit/4a6bfd3f35551094d0543bf5ba72f3105bfc70e7) by implementing ``getobjbound``, but this code segfaults. Am I doing something wrong?

### CODE REVIEW

**Comment by fserra** [comment]
Oh, this bad... we decided to call SCIPfreeTransform after it is solved (inside CSIPsolve), but the function you are calling: SCIPgetDualbound cannot be called in the stage that SCIP is after calling SCIPfreeTransform.  
I guess we could store the dual bound in CSIP_MODEL, right after SCIPsolve is called in CSIPsolve, but I don't know how scalable that solution is

**Comment by mlubin** [comment]
Doesn't seem like a bad idea to store it in the CSIP_MODEL.

**Comment by mlubin** [comment]
Updated the PR, this seems to work. Merge if you like it

**Comment by leethargo** [comment]
Thanks!

**Pull request merged**
